// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGpou2u8GxfIuS_OYP5QxExqZFND7Doo8',
    appId: '1:628624317094:android:cafd2a166321279983b267',
    messagingSenderId: '628624317094',
    projectId: 'ezdehar-app',
    storageBucket: 'ezdehar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4GmxE3rJdw7-6eIyqP0FKbgB7vwg_gmo',
    appId: '1:628624317094:ios:7584097af985998483b267',
    messagingSenderId: '628624317094',
    projectId: 'ezdehar-app',
    storageBucket: 'ezdehar-app.appspot.com',
    androidClientId: '628624317094-1buo3fuj18fb4eu9rpj5bakfmn99s30b.apps.googleusercontent.com',
    iosClientId: '628624317094-dg7lk86hcv3ihse7ritnak0ilq7t48fg.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.ezdiharApps',
  );
}
